manifest:

  projects:
    - name: zephyr
      url: https://github.com/zephyrproject-rtos/zephyr
      revision: v3.5.0
      path: zephyr
      west-commands: scripts/west-commands.yml
      import:
        name-allowlist:
          - cmsis
          - hal_stm32

    - name: st25dv
      url: https://github.com/faust-computer/st25dv
      revision: main
      path: modules/lib/st25dv

    - name: gps-sam-m10q
      url: https://github.com/faust-computer/gps-sam-m10q
      revision: main
      path: modules/lib/gps-sam-m10q

  self:
    path: gps-playground
